### ISSUE TITLE
Suggestion:  GPURamDrive uses graphics card VRAM for cache; integration

### ISSUE THREAD

**Issue by Logic-Elliven** [Zero3K/ERAM#31]
Hi Zero3K

I'm not a dev.
I just want to make you aware of GPURamDrive:
It enables one to use the, mostly inactive unless gaming etc, VRAM on a graphics card as a Ram Disk.

As most people's DRAM is otherwise occupied (prefetch, superfetch, etc) using RAM that is sitting idle makes a LOT of sense..!?  :)

The software is proof of concept and thus quite slow, but can probably be adapted to ERAM and optimised quite easily..??

Original software Link:
https://github.com/prsyahmi/GpuRamDrive
But it does NOT work on AMD Graphics Cards.
Here is a version that does:
https://github.com/brzz/GpuRamDrive/releases

**Comment by chrischris888** [comment]
@Zero3k

Hi,
Please help me with these questions:

1. If I install ERAM or DATARAM on my Windows XP, in order to add 1 more GB of RAM, will this solve the blue screen issue after MyPal 68 crashes the windows ?
2. Shall I wait for a new MyPal upgraded version ?
3. Does ERAM or DATARAM allow for using the extra ram for browser cache in order to avoid crashing into blue screen ?

I tahnk you verymuch !

**Comment by Zero3K** [comment]
1. They do not work that way. They just create a drive that uses RAM.
2 and 3. It is probably something else causing the BSOD.

**Comment by chrischris888** [comment]
@Zero3K 

Thank you very much ! Already I was very scared when I saw how complex and difficult the DATARAM installation is, by reading almost 100 pages of blogs.

However, I did one thing : I changed in MyComputer > System Properties > Advanced > Performance > and set from "system managed size" to "custom size" of RAM and I made it 5362 MB. I saw some improvement, ... not much but is ok.

And I can add additional 4GB of RAM on the available slots in order to get 8 GB and then set the /PAE in the BOOT.INI file ... and it may or may not be possible to see another slight improvement. Already there have been checked the “Data Execution Prevention” tab for essential windows programs. I did not tried for "all programs except some". Maybe you may advise me. I did not changed the BOOT.INI file yet.

In the past 10 years using this computer I never saw a blue screen until now, when MyPal 68 have been released. But as I recall it is still experimental therefore later updates might solve these issues.

Thank you again !

**Comment by chrischris888** [comment]
@Zero3k

Hi,
It just happened a new blue screen incident after opening more then 14 tabs on MyPal 68 and I catched it with the bluescreenview_setup.exe and I am attaching the file

==================================================
Dump File         : Mini050422-01.dmp
Crash Time        : 04.05.2022 07:33:36
Bug Check String  : KERNEL_MODE_EXCEPTION_NOT_HANDLED
Bug Check Code    : 0x1000008e
Parameter 1       : 0xc0000005
Parameter 2       : 0xbf80fa77
Parameter 3       : 0xb06e9b08
Parameter 4       : 0x00000000
Caused By Driver  : win32k.sys
Caused By Address : win32k.sys+fa77
File Description  : Multi-User Win32 Driver
Product Name      : Microsoft® Windows® Operating System
Company           : Microsoft Corporation
File Version      : 5.1.2600.5512 (xpsp.080413-2105)
Processor         : 32-bit
Crash Address     : win32k.sys+fa77
Stack Address 1   : win32k.sys+df9e7
Stack Address 2   : win32k.sys+dff87
Stack Address 3   : win32k.sys+c146b
Computer Name     : 
Full Path         : C:\WINDOWS\Minidump\Mini050422-01.dmp
Processors Count  : 4
Major Version     : 15
Minor Version     : 2600
Dump File Size    : 98.304
Dump File Time    : 04.05.2022 07:34:32
==================================================

**Comment by Zero3K** [comment]
It is an issue with Windows XP itself. Please try upgrading to Windows 7 if possible.
